cd "$(dirname "$0")"
npm install gulp
npm install browser-sync
npm install gulp-sass
npm install gulp-rename
npm install gulp-imagemin
npm install gulp-uglify
npm install readable-stream
npm install del